### ISSUE TITLE
Konsep Project

### ISSUE THREAD

**Issue by yusuf26** [andrysunandarbl/rekweb-bl-1115-group6#1]
Melakukan pembuatan konsep project yang akan di kerjakan.

**Comment by yohaann** [comment]
Kami adalah solusi dari kegalauan dari kebanyakan ibu rumah tangga disaat ingin mencari resep sajian kuliner nusantara.
Disini menyediakan beragam resep kuliner nusantara yang lengkap dan tersaji secara higinis, dan lagi anda tidak perlu kawatir jika ingin mengetahui bumbu-bumbu dapur untuk setiap sajian kuliner di nusantara.
